const { validateGenerationRequest } = require("../../contracts");
const { hasExistingFeedback, toText } = require("../shared/normalizers");
const { applyPageFeedback } = require("../shared/applyPageFeedback");
const { WEEK_6_GUIDANCE } = require("./context");

const CONTEXT = Object.freeze({ courseKey: "tot-1", courseTitle: "TOT 1", weekNumber: 6, weekTitle: "Teacher Well-Being and Sustainable SEL Practices", guidance: WEEK_6_GUIDANCE });
const PAGE_TARGETS = Object.freeze({ "tot-1:week:6:page:6": 6, "tot-1:week:6:page:8": 8, "tot-1:week:6:page:10": 10 });
const STEP_TARGETS = Object.freeze({
  ...Object.fromEntries([2,3,4,5,6,7].map((stepId) => [`tot-1:week:6:page:4:step:${stepId}`, { page: 4, stepId }])),
  ...Object.fromEntries([3,4,5,6,7,8,10,9].map((stepId) => [`tot-1:week:6:page:12:step:${stepId}`, { page: 12, stepId }]))
});
const FREQUENCY = Object.freeze({ A: "Never", B: "Occasionally", C: "Frequently", D: "Always" });
const BURNOUT = Object.freeze(["I often feel emotionally drained.", "I feel disconnected from my students.", "I get easily irritated by small things.", "I struggle to sleep or feel rested.", "I feel constantly behind or overwhelmed by responsibilities.", "I experience headaches, tension, or stomach issues during work."]);
const SUPPORT_ITEMS = Object.freeze(["Close colleagues or team members", "Immediate family", "A trusted friend", "Daily self-care practices", "Calming classroom routines", "Positive relationships with students", "School counsellor", "Mentor or senior colleague", "Online support groups", "School leadership", "School wellness programmes", "SEL workshops", "Parents or caregivers", "Peer teacher networks"]);
const PLAN_QUESTIONS = Object.freeze({ 3: "Why does SEL matter to you as a teacher?", 4: "Which three SEL or Positive Psychology skills will you focus on?", 5: "How will you integrate SEL into teaching and routines?", 6: "How will you model SEL and positivity?", 7: "What support will keep you consistent?", 8: "What two small actions will you take in the next two weeks?", 10: "How will sharing the plan support collaboration and encouragement?", 9: "What encouragement or reminder do you want to leave yourself?" });
const hasStep = (feedback, id) => Array.isArray(feedback) && feedback.some((item) => Number(item?.stepId) === id && Boolean(toText(item?.value)));
const add = (targets, activity, id, question, answer, type="reflection") => { const text=toText(answer); if(!activity||!text||hasStep(activity.feedback,id))return; targets.push({targetId:`tot-1:week:6:page:${activity.page}:step:${id}`,activityLabel:`Activity ${Number(activity.page)/2} - Response ${id}`,question,answer:text,responseType:type}); };
const entry = (answer,id,index) => { const item=Array.isArray(answer)?answer.find((x)=>Number(x?.stepId??x?.id)===id)||answer[index]:undefined; return item?.value??item; };
const dragValue = (answer) => Array.isArray(answer) ? answer.find((item)=>item?.value&&typeof item.value==="object")?.value : null;

const buildTot1Week6Request = ({requestId,activities}) => {
  if(!Array.isArray(activities))throw new TypeError("TOT 1 Week 6 activities must be an array"); const byPage=new Map(activities.map((a)=>[Number(a?.page),a])); const targets=[];
  const p4=byPage.get(4); [2,3,4,5,6,7].forEach((id,i)=>{const raw=toText(entry(p4?.answer,id,i));add(targets,p4,id,BURNOUT[i],FREQUENCY[raw]||raw,"single_select");});
  [[6,"Activity 2","Write three ways you recharge when you feel burnout."],[8,"Activity 3","Describe a recent teaching moment that made you grateful."]].forEach(([page,label,question])=>{const a=byPage.get(page);const answer=page===6&&Array.isArray(a?.answer)?a.answer.map((item,index)=>`${index+1}. ${toText(item?.value??item)}`).filter((item)=>!item.endsWith(". ")).join("\n"):toText(a?.answer);if(a&&answer&&!hasExistingFeedback(a.feedback))targets.push({targetId:`tot-1:week:6:page:${page}`,activityLabel:label,question,answer,responseType:"reflection"});});
  const p10=byPage.get(10),drag=dragValue(p10?.answer); if(p10&&drag&&!hasExistingFeedback(p10.feedback)){const answer=SUPPORT_ITEMS.map((item,i)=>{const key=Object.entries(drag).find(([,v])=>Array.isArray(v)&&v.map(Number).includes(i))?.[0];return `${item}: ${{green:"Inner Circle",orange:"Middle Circle",red:"Outer Circle"}[key]||"Unplaced"}`;}).join("\n");targets.push({targetId:"tot-1:week:6:page:10",activityLabel:"Activity 4",question:"Place each source of support in your inner, middle, or outer circle.",answer,responseType:"drag_and_drop"});}
  const p12=byPage.get(12),a=p12?.answer||{};
  add(targets,p12,3,PLAN_QUESTIONS[3],a.step_3?.mainInput); add(targets,p12,4,PLAN_QUESTIONS[4],a.step_4?.mainInput);
  const selected=Object.entries(a.step_5?.checkboxes||{}).filter(([,v])=>v).map(([k])=>k.replaceAll("_"," ")).join(", "); add(targets,p12,5,PLAN_QUESTIONS[5],`Methods: ${selected}\nOther: ${toText(a.step_5?.others_)}\nPlan: ${toText(a.step_5?.my_integration_plan__brief_description__)}`);
  add(targets,p12,6,PLAN_QUESTIONS[6],a.step_6?.mainInput); add(targets,p12,7,PLAN_QUESTIONS[7],a.step_7?.mainInput); add(targets,p12,8,PLAN_QUESTIONS[8],`1. ${toText(a.step_8?.input1)}\n2. ${toText(a.step_8?.input2)}`); add(targets,p12,10,PLAN_QUESTIONS[10],a.step_8?.collaboration); add(targets,p12,9,PLAN_QUESTIONS[9],a.step_9?.mainInput);
  if(!targets.length)return null;const {error,value}=validateGenerationRequest({requestId,context:CONTEXT,targets});if(error)throw new TypeError(`Invalid TOT 1 Week 6 feedback request: ${error.message}`);return value;
};
const applyTot1Week6Feedback=({activities,response})=>{if(!Array.isArray(response?.results))throw new TypeError("Feedback results must be an array");const pages=response.results.filter(r=>PAGE_TARGETS[r.targetId]),steps=response.results.filter(r=>STEP_TARGETS[r.targetId]);if(pages.length+steps.length!==response.results.length)throw new TypeError("Unknown feedback target");const updated=applyPageFeedback({activities,results:pages,targetPages:PAGE_TARGETS}),adds=new Map();steps.forEach(r=>{if(r.status==="skipped")return;const value=toText(r.feedback);if(r.status!=="ready"||!value)throw new TypeError(`Invalid or empty feedback result for target: ${r.targetId}`);const t=STEP_TARGETS[r.targetId];if(!adds.has(t.page))adds.set(t.page,new Map());adds.get(t.page).set(t.stepId,value);});return updated.map(a=>{const p=adds.get(Number(a?.page));if(!p)return a;const feedback=Array.isArray(a.feedback)?a.feedback.map(x=>({...x})):[];p.forEach((value,id)=>{const old=feedback.find(x=>Number(x?.stepId)===id);if(old)old.value=value;else feedback.push({stepId:id,value});});return{...a,feedback};});};
const tot1Week6Integration=Object.freeze({buildRequest:buildTot1Week6Request,applyFeedback:applyTot1Week6Feedback});module.exports={applyTot1Week6Feedback,buildTot1Week6Request,tot1Week6Integration};
